version: '3'

services:
  steemit_daemon:
    build: .
    container_name: zolna_steemit_daemon
    # need the sleep to wait for the DB service to get up and running
    command: ["./wait-for-database.sh", "database", "5432", "--", "bundle exec rake daemons:run_zolna"]
    depends_on:
      - database
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=${DATABASE_URL:-postgres://database:5432}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - CURRENT_YEAR=${CURRENT_YEAR}
      - STEEM_WIF_GREENSPUDTRADES=null
      - STEEM_WIF_ZOLNA=${STEEM_WIF_ZOLNA}
      - STEEM_WIF_ZOLNAREPORT=${STEEM_WIF_ZOLNA}
      - ZOLNA_VIDEOS_SOURCE_DIR=${ZOLNA_VIDEOS_SOURCE_DIR}
    networks:
      - freespeech
      - ipfs_localhost
    ports:
      - ${HTTP_PORT:-80}:32013
    tty: true
    volumes:
      - .:/app
      - ${SHARE_CONTENT_DIR}:/app/data/share_content
      - ${ZOLNA_VIDEOS_SERVER_SOURCE_DIR}:/app/data/zolnareport_source
#      - ./log:/app/log
#      - ./public/assets:/app/public/assets

  database:
    container_name: zolna_database
    image: "postgres:9.6.5-alpine"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_DATA_DIR: ${DB_DATA_DIR}
    networks:
      - freespeech
#    ports:
#      - "5444:5432"
    volumes:
      - "./data/postgres_data_965:${DB_DATA_DIR}"
      - "./data/postgres_backups:/postgres_backups"

  ipfs:
    command: "daemon --migrate=true --enable-namesys-pubsub"
    container_name: ipfs
    environment:
      IPFS_FD_MAX: 32768
    image: jbenet/go-ipfs:master
    networks:
      - ipfs_localhost
    ports:
      - "8080:8080"
      - "4001:4001"
      - "127.0.0.1:5001:5001"
    volumes:
      - "./data/docker-ipfs-data:/data/ipfs"
      - ${SHARE_CONTENT_DIR}:/share_content
      - "./tmp/ipfs-docker-staging:/export"
      - ${ZOLNA_VIDEOS_SERVER_SOURCE_DIR}:/zolnareport_source

networks:
  freespeech:
  ipfs_localhost:
    external: true
