version: '3'

services:
  steemit_daemon:
    build: .
    container_name: zolna_steemit_daemon
    # need the sleep to wait for the DB service to get up and running
    command: ["./wait-for-database.sh", "database", "5432", "--", "bundle exec rake daemons:run_zolna"]
#    command: ["./wait-for-database.sh", "database", "5432", "--", "bundle exec rails c"]
    depends_on:
      - database
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=${DATABASE_URL:-postgres://database:5432}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - STEEM_WIF_GREENSPUDTRADES=null
      - STEEM_WIF_ZOLNA=${STEEM_WIF_ZOLNA}
      - STEEM_WIF_ZOLNAREPORT=${STEEM_WIF_ZOLNA}
    networks:
      - freespeech
    ports:
      - ${HTTP_PORT:-80}:3000
    tty: true
    volumes:
      - .:/app
#      - ./log:/app/log
#      - ./public/assets:/app/public/assets

  database:
    container_name: zolna_database
    image: "postgres:9.6.5-alpine"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_DATA_DIR: ${DB_DATA_DIR}
    networks:
      - freespeech
#    ports:
#      - "5444:5432"
    volumes:
      - "./data/postgres_data_965:${DB_DATA_DIR}"
      - "./data/postgres_backups:/postgres_backups"

networks:
  freespeech:
