template: &template
  steemit_wif_zolna: <%= ENV.fetch('STEEM_WIF_ZOLNA') %>


development: &development
  <<: *template
  secret_key_base: ea066648652a0190666b0e81ea3e3f56bd4c330f65340b41a1a3af4b210d4d4f970b4365d9e8e46440e6ac6b31d3c2e8319cbdbf2d76aedf47206c4d66005453

test:
  secret_key_base: 399ee25e10669b7f639863f38dbecb710dbed5bb9165dad984a48c9f62efd840e4cbb9058b35be1ff23a4790c4e95452929ffc119e23df2ad02971d9d2482c78

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
